apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-challenge

  template:
    metadata:
      labels:
        app: fiap-challenge
    spec:
      containers:
        - name: fiap-challenge-order-postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          ports:
            - containerPort: 5432
        - name: fiap-challenge-order-api
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 8080
