apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-dep
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: postgres-container
          image: postgres
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          ports:
            - containerPort: 3020
        - name: challenge-container
          image: 891377406064.dkr.ecr.us-east-1.amazonaws.com/challenge-ecr:latest
          env:
            - name: AKIA47CR32BYIKGP7N36
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: hn1YOdQr1LtiazjmsdJ6P7+YtBeeXTXdXi3i663y
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 8080
